### ISSUE TITLE
Release to production

### ISSUE THREAD

**Issue by chaspy** [chaspy/favsearch#32]
## TODO
to alfa release

### High priority
- [x] Remove logout https://github.com/chaspy/favsearch/pull/33
- [x] Consider whether storing secret in cookie is complete https://github.com/chaspy/favsearch/pull/37
- [x] Update Social link https://github.com/chaspy/favsearch/pull/35
- [x] Display the tweet's user name and searchable user https://github.com/chaspy/favsearch/pull/36

### Mid(do not now)
- [ ] Restrict to https https://github.com/chaspy/favsearch/issues/38
- [ ] Emphasis on matching parts in incremental search https://github.com/chaspy/favsearch/issues/39
- [ ] Ambiguous match of hiragana, katakana, capital letters, lower case letters https://github.com/chaspy/favsearch/issues/40
- [ ] Page nation https://github.com/chaspy/favsearch/issues/41
- [ ] Get more than 200 favorite records https://github.com/chaspy/favsearch/issues/6

**Comment by chaspy** [comment]
ok, let's release 🚀
